src/Riktig.Web/Models/GetImagesViewModel.cs
namespace Riktig.Web.Models
{
    public class GetImagesViewModel
    {
        public string[] SourceAddress { get; set; }
    }
}

src/Riktig.Web/Models/ImageResultsViewModel.cs
namespace Riktig.Web.Models
{
    using System;
    using System.Collections.Generic;


    public class ImageResultsViewModel
    {
        readonly IEnumerable<Uri> _images;

        public ImageResultsViewModel(IEnumerable<Uri> images)
        {
            _images = images;
        }

        public IEnumerable<Uri> Images
        {
            get { return _images; }
        }
    }
}

src/Riktig.Web/Models/ImageViewModel.cs
namespace Riktig.Web.Models
{
    using System.ComponentModel.DataAnnotations;


    public class ImageViewModel
    {
        [Required]
        public string SourceAddress { get; set; }
    }
}

src/Riktig.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Riktig.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            ViewBag.Message = "Modify this template to jump-start your ASP.NET MVC application.";

            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your app description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

src/Riktig.Web/Controllers/ImageController.cs
namespace Riktig.Web.Controllers
{
    using System;
    using System.Collections.Concurrent;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Contracts.Api;
    using Magnum.Extensions;
    using MassTransit;
    using Models;
    using RapidTransit.Core;


    public class ImageController :
        Controller
    {
        readonly IServiceBus _bus;
        readonly ImageServiceSettings _settings;

        public ImageController(IHostServiceBus bus, ImageServiceSettings settings)
        {
            _bus = bus;
            _settings = settings;
        }

        //
        // GET: /Image/

        public ActionResult Index()
        {
            return View();
        }

        //
        // GET: /Image/Create

        public ActionResult RequestImage()
        {
            return View();
        }

        //
        // POST: /Image/Create

        [HttpPost]
        public ActionResult RequestImage(ImageViewModel model)
        {
            try
            {
                _bus.GetEndpoint(_settings.ImageTrackingServiceAddress)
                    .Send(new RequestImageCommand(new Uri(model.SourceAddress)));

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }


        public ActionResult GetImages()
        {
            return View();
        }

        //
        // POST: /Image/Create

        [HttpPost]
        public async Task<ActionResult> RequestImages(GetImagesViewModel model)
        {
            try
            {
                IEndpoint endpoint = _bus.GetEndpoint(_settings.ImageTrackingServiceAddress);

                var results = new ConcurrentBag<Uri>();

                IEnumerable<Task> requests = model
                    .SourceAddress
                    .Where(x => !string.IsNullOrEmpty(x) && Uri.IsWellFormedUriString(x, UriKind.RelativeOrAbsolute))
                    .Select(address =>
                        {
                            return endpoint.SendRequestAsync(_bus,
                                new RequestImageCommand(new Uri(address)), x =>
                                    {
                                        x.Handle<ImageRequestCompleted>(msg => results.Add(msg.LocalAddress));
                                        x.Handle<ImageRequestFaulted>(msg => { });
                                        x.HandleTimeout(30.Seconds(), () => { });
                                    }).Task;
                        });

                return await Task.WhenAll(requests)
                                 .ContinueWith(tasks => { return PartialView("ImageResults",new ImageResultsViewModel(results)); });
            }
            catch
            {
                return View();
            }
        }


        class RequestImageCommand :
            RequestImage
        {
            public RequestImageCommand(Uri sourceAddress)
            {
                RequestId = NewId.NextGuid();
                Timestamp = DateTime.UtcNow;

                SourceAddress = sourceAddress;
            }

            public Guid RequestId { get; private set; }
            public DateTime Timestamp { get; private set; }
            public Uri SourceAddress { get; private set; }
        }
    }
}

src/Riktig.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<article>
    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>

    <p>
        Use this area to provide additional information.
    </p>
</article>

<aside>
    <h3>Aside Title</h3>
    <p>
        Use this area to provide additional information.
    </p>
    <ul>
        <li>@Html.ActionLink("Home", "Index", "Home")</li>
        <li>@Html.ActionLink("About", "About", "Home")</li>
        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
    </ul>
</aside>

src/Riktig.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<hgroup class="title">
    <h1>@ViewBag.Title.</h1>
    <h2>@ViewBag.Message</h2>
</hgroup>

<section class="contact">
    <header>
        <h3>Phone</h3>
    </header>
    <p>
        <span class="label">Main:</span>
        <span>425.555.0100</span>
    </p>
    <p>
        <span class="label">After Hours:</span>
        <span>425.555.0199</span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Email</h3>
    </header>
    <p>
        <span class="label">Support:</span>
        <span><a href="mailto:Support@example.com">Support@example.com</a></span>
    </p>
    <p>
        <span class="label">Marketing:</span>
        <span><a href="mailto:Marketing@example.com">Marketing@example.com</a></span>
    </p>
    <p>
        <span class="label">General:</span>
        <span><a href="mailto:General@example.com">General@example.com</a></span>
    </p>
</section>

<section class="contact">
    <header>
        <h3>Address</h3>
    </header>
    <p>
        One Microsoft Way<br />
        Redmond, WA 98052-6399
    </p>
</section>

src/Riktig.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                To learn more about ASP.NET MVC visit
                <a href="http://asp.net/mvc" title="ASP.NET MVC Website">http://asp.net/mvc</a>.
                The page features <mark>videos, tutorials, and samples</mark> to help you get the most from ASP.NET MVC.
                If you have any questions about ASP.NET MVC visit
                <a href="http://forums.asp.net/1146.aspx/1?MVC" title="ASP.NET MVC Forum">our forums</a>.
            </p>
        </div>
    </section>
}
<h3>We suggest the following:</h3>
<ol class="round">
    <li class="one">
        <h5>Getting Started</h5>
        ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
        enables a clean separation of concerns and that gives you full control over markup
        for enjoyable, agile development. ASP.NET MVC includes many features that enable
        fast, TDD-friendly development for creating sophisticated applications that use
        the latest web standards.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245151">Learn more…</a>
    </li>

    <li class="two">
        <h5>Add NuGet packages and jump-start your coding</h5>
        NuGet makes it easy to install and update free libraries and tools.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245153">Learn more…</a>
    </li>

    <li class="three">
        <h5>Find Web Hosting</h5>
        You can easily find a web hosting company that offers the right mix of features
        and price for your applications.
        <a href="http://go.microsoft.com/fwlink/?LinkId=245157">Learn more…</a>
    </li>
</ol>

src/Riktig.Web/Views/Image/GetImages.cshtml
@model Riktig.Web.Models.GetImagesViewModel

@{
    ViewBag.Title = "Get Images";
}

<h2>Request Image</h2>


@using (Ajax.BeginForm("RequestImages", "Image", new AjaxOptions{ HttpMethod="POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "results"}))
{
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Address</legend>
        
        @for (var i = 0; i < 5; i++)
        {
            <div class="editor-label">
                @Html.LabelFor(model => model.SourceAddress)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.SourceAddress[i])
                @Html.ValidationMessageFor(model => model.SourceAddress[i])
            </div>
        }
        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Ajax.ActionLink("Dogs and Cats", "RequestImages", new { 
        SourceAddress = new[] 
            { 
                "http://i.imgur.com/Iroma7d.png", "http://i.imgur.com/NK8eZUe.jpg"
            } 
        }, new AjaxOptions
            {
                HttpMethod = "POST",
                InsertionMode = InsertionMode.Replace,
                UpdateTargetId = "results"
            })
</div>


<div>
    <br/>
    @Html.ActionLink("Back to Pending Images", "Index")
</div>

<div id="results">
    
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Riktig.Web/Views/Image/ImageResults.cshtml
@model Riktig.Web.Models.ImageResultsViewModel

@foreach (var img in @Model.Images)
{
            <div>
                <img src="/ImageCache/@Path.GetFileName(img.AbsolutePath)"/>
            </div>
}

src/Riktig.Web/Views/Image/Index.cshtml
@{
    ViewBag.Title = "Image Requests";
}
@section featured {
    <section class="featured">
        <div class="content-wrapper">
            <hgroup class="title">
                <h1>@ViewBag.Title.</h1>
                <h2>@ViewBag.Message</h2>
            </hgroup>
            <p>
                This should show the list of image requests that are pending...
            </p>
        </div>
    </section>
}
<h3>Pending Image Requests</h3>
<ol class="round">
    <li class="one">
        This would be one...
    </li>
</ol>

src/Riktig.Web/Views/Image/Request.cshtml
@model Riktig.Web.Models.ImageViewModel

@{
    ViewBag.Title = "Request Image";
}

<h2>Request Image</h2>


@using (Html.BeginForm("Request", "Image")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Address</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SourceAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SourceAddress)
            @Html.ValidationMessageFor(model => model.SourceAddress)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Ajax.ActionLink("Cat", "Request", new { SourceAddress = new Uri("http://i.imgur.com/Iroma7d.png")},new AjaxOptions {HttpMethod = "POST"})
    <br/>
    @Ajax.ActionLink("Good Dog", "Request", new { SourceAddress = new Uri("http://i.imgur.com/NK8eZUe.jpg")},new AjaxOptions {HttpMethod = "POST"})
</div>


<div>
    <br/>
    @Html.ActionLink("Back to Pending Images", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Riktig.Web/Views/Image/RequestImage.cshtml
@model Riktig.Web.Models.ImageViewModel

@{
    ViewBag.Title = "Request Image";
}

<h2>Request Image</h2>


@using (Html.BeginForm("RequestImage", "Image")) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Address</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.SourceAddress)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.SourceAddress)
            @Html.ValidationMessageFor(model => model.SourceAddress)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Ajax.ActionLink("Cat", "RequestImage", new { SourceAddress = new Uri("http://i.imgur.com/Iroma7d.png")},new AjaxOptions {HttpMethod = "POST"})
    <br/>
    @Ajax.ActionLink("Good Dog", "RequestImage", new { SourceAddress = new Uri("http://i.imgur.com/NK8eZUe.jpg")},new AjaxOptions {HttpMethod = "POST"})
</div>


<div>
    <br/>
    @Html.ActionLink("Back to Pending Images", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Riktig.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - My ASP.NET MVC Application</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("your logo here", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("About", "About", "Home")</li>
                            <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                            <li>@Html.ActionLink("Request Image", "RequestImage", "Image")</li>
                            <li>@Html.ActionLink("Get Images", "GetImages", "Image")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - My ASP.NET MVC Application</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>